<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="rgbd_camera_length" value="0.015" />
<xacro:property name="rgbd_camera_width" value="0.05" />
<xacro:property name="rgbd_camera_height" value="0.05" />
<xacro:property name="rgbd_camera_mass" value="0.1" />

<xacro:property name="base_length" value="0.5" />
<xacro:property name="base_width" value="0.3" />
<xacro:property name="base_height" value="0.08" />

<xacro:macro name="rgbd_camera" params="prefix">

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <link name="${prefix}rgbd_camera_link">
        <visual>
            <geometry>
                <box size="${rgbd_camera_length} ${rgbd_camera_width} ${rgbd_camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${rgbd_camera_length} ${rgbd_camera_width} ${rgbd_camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="${rgbd_camera_mass}"/>
            <inertia ixx="${(1/12) * rgbd_camera_mass * (rgbd_camera_width * rgbd_camera_width + rgbd_camera_height * rgbd_camera_height)}" 
                iyy="${(1/12) * rgbd_camera_mass * (rgbd_camera_length * rgbd_camera_length + rgbd_camera_height * rgbd_camera_height)}" 
                izz="${(1/12) * rgbd_camera_mass * (rgbd_camera_length * rgbd_camera_length + rgbd_camera_width * rgbd_camera_width)}" 
                ixy="0" ixz="0" iyz="0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </inertial>
    </link>

    <joint name="${prefix}base_rgbd_camera_joint" type="fixed">
        <parent link="${prefix}base_link"/>
        <child link="${prefix}rgbd_camera_link"/>
        <origin xyz="${-(base_length/2)-(rgbd_camera_length/2)} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="rgbd_optical_frame"/>
    <joint name="rgbd_optical_joint" type="fixed">
      <parent link="rgbd_camera_link"/>
      <child link="rgbd_optical_frame"/>
      <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
    </joint>
    
    <gazebo reference="${prefix}rgbd_camera_link">
        <sensor type="rgbd_camera" name="rgbd_camera">
            <always_on>1</always_on>
            <update_rate>30.0</update_rate>
            <camera>
                <horizontal_fov>1.0472</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10.0</far>
                </clip>
            </camera>
            <frame>rgbd_camera_link</frame>
            <topic>/camera</topic>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
    
</xacro:macro>
</robot>